
version: 1.0.{build}
image:
#- Visual Studio 2019
- Ubuntu

environment:
  matrix:
    - ARCH: amd64
    #- ARCH: arm64v8

#matrix:
#  exclude:
#    - image: Visual Studio 2019
#      ARCH: arm64v8

build_script:
  - ps: ./build.ps1

deploy_script:
  - ps: ./deploy.ps1
